#' Retrieve tree-ring fire history data from the IMPD
#'
#'
#' @param studyCode Provides a unique reference to retrieve an FHX file from the
#'   IMPD. The `studyCode` field is available in the data frame generated by [build_impd_meta()]
#'
#' @importFrom httr parse_url build_url
#' @importFrom stringr str_glue
#' @importFrom burnr read_fhx
#'
#' @export
#' @examples
#' fsr <- get_impd_fhx("USFSR001")
#' burnr::plot(fsr)


get_impd_fhx <- function(studyCode) {
  file_url <- parse_url("https://www.ncei.noaa.gov/")
  file_url$scheme <- "https"
  file_url$path <- str_glue("pub/data/paleo/firehistory/firescar/northamerica/",
                            "{tolower(studyCode)}.fhx")
  read_fhx(build_url(file_url))
}
