#' Retrieve tree-ring fire history data from the International Multiproxy
#' Paleofire Database (IMPD)
#'
#' @param studyCode Provides a unique reference to retrieve an FHX file from the
#'   IMPD. The `studyCode` field is available in the data frame generated by
#'  [search_impd()]
#'
#' @details The function pulls FHX file(s) from the NOAA ftp server at
#'   [https://www.ncei.noaa.gov/pub/data/paleo/firehistory/firescar/northamerica/](https://www.ncei.noaa.gov/pub/data/paleo/firehistory/firescar/northamerica/).
#'    Therefore, the success of the function largely depends on the availability
#'   of the server. Sometimes it may not work due to network issues, so patience
#'   may be required. Currently, the function limits searches to a single study
#'   code. Use loops, or `purrr`-style iterative calls to expedite the retrieval
#'   of multiple files.
#'
#' @return Retrieved files are in FHX format, which are read in and formatted
#'   with the `burnr` library. See
#'   [https://ltrr-arizona-edu.github.io/burnr/reference/read_fhx.html](https://ltrr-arizona-edu.github.io/burnr/reference/read_fhx.html)
#'    for more details.
#'
#' @importFrom httr parse_url build_url
#' @importFrom stringr str_glue
#' @importFrom burnr read_fhx
#'
#' @export
#' @examples
#' ## Not run:
#' \dontrun{
#' fsr <- get_impd_fhx("USFSR001")
#' burnr::plot_demograph(fsr)
#' }
#' ## End (Not run)


get_impd_fhx <- function(studyCode) {
  if (length(studyCode) > 1) stop("Please supply only 1 study code")

  file_url <- parse_url("https://www.ncei.noaa.gov/")
  file_url$scheme <- "https"
  file_url$path <- str_glue("pub/data/paleo/firehistory/firescar/northamerica/",
                            "{tolower(studyCode)}.fhx")
  read_fhx(build_url(file_url))
}

